name: Get Poetry Version

description: Checkout target ref, get version from poetry, and restore previous state

inputs:
  ref:
    description: Git ref to checkout (branch, tag, commit SHA)
    required: true

outputs:
  version:
    description: The version of the project from poetry
    value: ${{ steps.set-version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Save current ref
      id: save-ref
      shell: bash
      run: echo "current_ref=$(git rev-parse --abbrev-ref HEAD)" >> "$GITHUB_OUTPUT"

    - name: Checkout specific ref
      if: inputs.checkout-ref
      shell: bash
      run: git checkout ${{ inputs.checkout-ref }}

    - name: Get version from pyproject.toml
      id: get-version
      shell: bash
      run: |
        VERSION=$(poetry version --short)
        echo "version=$VERSION" >> "$GITHUB_OUTPUT"
        echo "Version: $VERSION at ${{ inputs.ref }}"

    - name: Restore original ref
      if: inputs.checkout-ref
      shell: bash
      run: git checkout ${{ steps.save-ref.outputs.current_ref }}
