name: "Compare PyPI Version"
description: "Compare current version with latest version on PyPI"
inputs:
  package-name:
    description: "PyPI package name to check"
    required: true
  current-version:
    description: "Current version to compare"
    required: true
outputs:
  pypi-version:
    description: "Latest version found on PyPI"
    value: ${{ steps.check-pypi.outputs.pypi_version }}
  is-newer:
    description: "Whether current version is newer than PyPI version"
    value: ${{ steps.check-pypi.outputs.is_newer }}

runs:
  using: "composite"
  steps:
    - name: Install jq
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Check PyPI version and compare
      id: check-pypi
      shell: bash
      run: |
        PACKAGE_NAME="${{ inputs.package-name }}"
        CURRENT_VERSION="${{ inputs.current-version }}"

        echo "Checking package: $PACKAGE_NAME"
        echo "Current version: $CURRENT_VERSION"

        # Fetch PyPI information
        response=$(curl -s "https://pypi.org/pypi/$PACKAGE_NAME/json" || echo "{}")

        pypi_version=$(echo "$response" | jq --raw-output "select(.releases != null) | .releases | keys_unsorted | last // empty")

        if [ -z "$pypi_version" ] || [ "$pypi_version" = "null" ]; then
          echo "Package not found on PyPI or no releases available."
          pypi_version="0.0.0"
        fi

        echo "Latest version on PyPI: $pypi_version"
        echo "pypi_version=$pypi_version" >> "$GITHUB_OUTPUT"

        # Compare versions using sort -rV
        if [ "$CURRENT_VERSION" = "$pypi_version" ]; then
          echo "❌ Current version equals PyPI version ($CURRENT_VERSION)"
          echo "is_newer=false" >> "$GITHUB_OUTPUT"
          exit 1
        elif [ "$(printf '%s\n' "$pypi_version" "$CURRENT_VERSION" | sort -rV | head -n 1)" = "$CURRENT_VERSION" ]; then
          echo "✅ Current version ($CURRENT_VERSION) is newer than PyPI version ($pypi_version)"
          echo "is_newer=true" >> "$GITHUB_OUTPUT"
        else
          echo "❌ Current version ($CURRENT_VERSION) is older than PyPI version ($pypi_version)"
          echo "is_newer=false" >> "$GITHUB_OUTPUT"
          exit 1
        fi
